### ISSUE TITLE
Why checking undeclared rules?

### ISSUE THREAD

**Issue by sksms17456** [stylelint-scss/stylelint-config-standard-scss#10]
I am migrating to stylelint version 13.13.1 to 14.
this is my stylelint dependancy
```
    "stylelint": "^14.1.0",
    "stylelint-config-standard-scss": "^3.0.0",
```
this is my .stylelintrc
```
module.exports = {
  extends: ['stylelint-config-standard-scss'],
  rules: {
    'at-rule-disallowed-list': ['extend'],
    'at-rule-no-unknown': null,
    'scss/at-rule-no-unknown': true,
    'color-named': 'never',
    'declaration-property-value-disallowed-list': {
      '/^border/': ['none'],
    },
    'font-weight-notation': 'numeric',
    'function-url-quotes': 'never',
    'property-no-unknown': [
      true,
      {
        ignoreSelectors: [':export']
      }
    ],
    'selector-class-pattern': '^([a-z][a-z0-9]*)(_[a-z0-9]+)*$',
    'shorthand-property-no-redundant-values': true,
    'string-quotes': 'single',
    'selector-pseudo-class-no-unknown': [
      true,
      {
        ignorePseudoClasses: ['export','external', 'global', 'local'],
      },
    ],
    'value-keyword-case': [
      'lower',
      {
        ignoreProperties: ['/^\\$/']
      }
    ],
```
![image](https://user-images.githubusercontent.com/19828721/143795734-373977c5-c244-4bad-a189-ad11a1266a2e.png)
For example, when I declare the above style, Stylint checks the rules that I did not declare.
I want to know why the rules I didn't declare are checked.

**Comment by kristerkari** [comment]
I'm not sure if I understood the problem correctly, but `stylelint-config-standard-scss` is extending `stylelint-config-standard` which has a bunch of rules enabled.

The rule that you mentioned comes from here: https://github.com/stylelint/stylelint-config-standard/blob/main/index.js#L30

**Comment by sksms17456** [comment]
@kristerkari 
thank you for comment,
If so, are the rules in stylelint-config-standard applied unconditionally? Is it possible to turn off certain rules?

**Comment by kristerkari** [comment]
@sksms17456 no problem at all :) It's good to ask if something is not clear.
