### ISSUE TITLE
Override/disable `media-query-no-invalid` rule

### ISSUE THREAD

**Issue by terrymun** [stylelint-scss/stylelint-config-standard-scss#120]
The latest version of stylelint introduces this new rule: [`media-query-no-invalid`](https://github.com/stylelint/stylelint/issues/6916), and this causes issues if users upgrade and forget to disable the rule manually. The rule is not recommended for pre-processed CSS ([source](https://stylelint.io/user-guide/rules/media-query-no-invalid/)):

> This rule is only appropriate for CSS. You should not turn it on for CSS-like languages, such as Sass or Less, as they have their own syntaxes.

Therefore it probably makes sense to add an override to disable this rule:

```
"media-query-no-invalid": null
```

Update: I am more than happy to create a pull request for this, but before I do it I'd love to hear what the owners think about adding this rule.

**Comment by jnoordsij** [comment]
I think this already has been adressed in https://github.com/stylelint-scss/stylelint-config-recommended-scss/commit/c95076bbf5a2a1443872241fa961388d074a23e6, and thus requires
1. a new release from `stylelint-config-recommended-scss`
2. a version bump of that in the `package.json` file here following that.

**Comment by kristerkari** [comment]
Sorry for the delay. I can cut a new release 👍

**Comment by kristerkari** [comment]
Done:
https://github.com/stylelint-scss/stylelint-config-standard-scss/releases/tag/v11.0.0
