### ISSUE TITLE
Cannot find module 'postcss/lib/stringifier'

### ISSUE THREAD

**Issue by NachoMM14** [stylelint-scss/stylelint-config-standard-scss#13]
I installed stylelint-config-standard-scss and add
{
  "extends": "stylelint-config-standard-scss"
} 
but when executed it gives the error: cannot find module 'postcss/lib/stringifier' Require stack: - node_modules/postcss-scss/lib/scss-stringifier.js

**Comment by kristerkari** [comment]
@NachoMM14 which version of postcss are you using?

**Comment by kristerkari** [comment]
This kind of sounds like the Postcss library would not be properly installed in your project, or that there would be an older version in use. Maybe you could check that first.

**Comment by NachoMM14** [comment]
I have it installed Postcss correctly in the version 8.4.5

![image](https://user-images.githubusercontent.com/95936373/151926266-54cdf314-7d42-4741-8dcd-70795c16d84a.png)

**Comment by Skowronek-Jaskula** [comment]
Maybe you've missed to install one of your configuration modules? I forgot about stylelint-config-recommended-scss and had the same problem. Now it's fixed :)

**Comment by NachoMM14** [comment]
@Skowronek-Jaskula Thank you very much for the contribution. It was that.
Solved!
