### ISSUE TITLE
Update to `stylelint-config-standard@25`?

### ISSUE THREAD

**Issue by Semigradsky** [stylelint-scss/stylelint-config-standard-scss#15]
https://github.com/stylelint/stylelint-config-standard/releases/tag/25.0.0

**Comment by kristerkari** [comment]
Sure, makes sense.

**Comment by Semigradsky** [comment]
And `stylelint-config-recommended-scss@6` 😄 
https://github.com/stylelint-scss/stylelint-config-recommended-scss/releases/tag/v6.0.0
