### ISSUE TITLE
'scss/dollar-variable-colon-space-after': 'always' conflicts with stylelint-prettier/recommended

### ISSUE THREAD

**Issue by kbrilla** [stylelint-scss/stylelint-config-standard-scss#165]
Currently `"scss/dollar-variable-colon-space-after"` is conigured as `always` which conflicts with prettier formating.

Those two are fighting for this code:

Prettier want:
```
$layered-shadow:
  0 1px 1px rgb(0 0 0 / 0.12),
  0 2px 2px rgb(0 0 0 / 0.12),
  0 4px 4px rgb(0 0 0 / 0.12),
  0 8px 8px rgb(0 0 0 / 0.12);
```

while `"scss/dollar-variable-colon-space-after": "always"`
```
$layered-shadow: 0 1px 1px rgb(0 0 0 / 0.12),
  0 2px 2px rgb(0 0 0 / 0.12),
  0 4px 4px rgb(0 0 0 / 0.12),
  0 8px 8px rgb(0 0 0 / 0.12);
```

switching to `"scss/dollar-variable-colon-space-after": "always-single-line"` succesfully resovles this infight in rules
https://github.com/stylelint-scss/stylelint-scss/blob/master/src/rules/dollar-variable-colon-space-after/README.md#always-single-line

Please consider changing this rule setting

**Comment by kristerkari** [comment]
Thanks! Fixed now with #156, so I'll release a new version.
