### ISSUE TITLE
Nested math.div not being recognized in certain configurations

### ISSUE THREAD

**Issue by anselmbradford** [stylelint-scss/stylelint-config-standard-scss#183]
I have two scss variables `$grid-gutter-width` and `$base-font-size-px`, which have the values `30px` and `16px`, respectively. For some reason, this causes problems in certain nested configurations of `math.div`. I get a `Unexpected unknown function "div"  function-no-unknown` error in stylelint.

Some examples where it comes up:

```
transform: translateX(
    math.div(math.div(-1 * $grid-gutter-width, 2), $base-font-size-px) + em
);
```

```
margin: 0 (math.div(math.div($grid-gutter-width, 2), $base-font-size-px) + em);
```

If I convert the variables to their hardcoded values, the linting errors go away. 

Or, in the first example, if I move the value to its own variable, that also makes it go away:

```
$translate-value: math.div(math.div(-1 * $grid-gutter-width, 2), $base-font-size-px) + em;
transform: translateX($translate-value);
```

Or, in the second example, if I remove the outer parentheses it will go away:

```
margin: 0 math.div(math.div($grid-gutter-width, 2), $base-font-size-px) + em;
```

I have other cases where `math.div` is nested and it passes no problem. The problem seems to be when it appears within an outer parentheses and has a variable inside.

**Comment by kristerkari** [comment]
@anselmbradford Thanks! Stylelint's `function-no-unknown` rule does not support SCSS, so you should use the rule `scss/function-no-unknown` instead.

**Comment by anselmbradford** [comment]
@kristerkari Thanks for that. I do have the `function-no-unknown` rule set in my config, so that was probably the issue. I'll close this.
