### ISSUE TITLE
Deprecation Warning: The "scss/at-import-partial-extension" rule is deprecated.

### ISSUE THREAD

**Issue by adgoncal** [stylelint-scss/stylelint-config-standard-scss#198]
@kristerkari When will a new release be published? I see the following deprecation warning when I run stylelint using `stylelint-config-standard-scss`:

```
Deprecation Warning: The "scss/at-import-partial-extension" rule is deprecated.
```

The rule `scss/at-import-partial-extension` has been deprecated and should be replaced with `scss/load-partial-extension`. 

This change has already been made to `stylelint-config-recommended-scss` on version v14.1.0, but the last published release for `stylelint-config-standard-scss` is still using v14.0.0. 

Dependabot has already bumped it in the main branch here, so a new release with the latest changes from the main branch would solve this issue.

**Comment by kristerkari** [comment]
Thanks @adgoncal !

I haven't noticed the deprecated rule since I don't use this config myself, but I can definitely create a new minor version that includes a fix.

**Comment by kristerkari** [comment]
Done: https://github.com/stylelint-scss/stylelint-config-standard-scss/releases/tag/v14.0.0
