### ISSUE TITLE
Loads of deprecation warnings?

### ISSUE THREAD

**Issue by mattdell** [stylelint-scss/stylelint-config-standard-scss#59]
I'm getting these warnings on a brand new setup.

<img width="649" alt="Screenshot 2023-02-09 at 17 05 40" src="https://user-images.githubusercontent.com/2536442/217886188-bc58e153-c486-4f79-b21a-c708aa14511c.png">

My `.stylelintrc.js` file is the following

```
module.exports = {
  extends: 'stylelint-config-standard-scss',
};
```

I am using these versions of the linter / config:

```
"stylelint": "^15.0.0",
"stylelint-config-standard-scss": "^6.1.0",
```

I'm surprised to see depcrecation warnings on the latest version of the config. Any ideas?

**Comment by mattdell** [comment]
Appears to be related: https://github.com/stylelint/stylelint/pull/6561

**Comment by kristerkari** [comment]
There is no support for stylelint v15 yet, but will try to get the dependencies/configs updated this weekend to get rid of the warnings.
