### ISSUE TITLE
Deprecated rule `block-closing-brace-newline-after`

### ISSUE THREAD

**Issue by sabertazimi** [stylelint-scss/stylelint-config-standard-scss#67]
```bash
Deprecation warnings:
 - The "block-closing-brace-newline-after" rule is deprecated.
```

https://github.com/stylelint-scss/stylelint-config-standard-scss/blob/88b820a96edda3ce7f0219d74e72eead7484a6e4/index.js#L14-L19

**Comment by kristerkari** [comment]
Fixed in a patch release:
https://github.com/stylelint-scss/stylelint-config-standard-scss/releases/tag/v7.0.1
